[project]
authors = ["timoverlaan <t.verlaan@tudelft.nl>"]
channels = ["nvidia", "conda-forge", "pytorch"]
name = "cropxr-example"
platforms = ["linux-64", "win-64"]
version = "0.1.0"
description = "Data and DL model example for CropXR project"


[system-requirements]
linux = "3.10"  # Lower for older kernel on DAIC
cuda = "12.4"  # (not necessary for processing)

[tasks]
# train = "python src/train.py"
# preprocess = "python src/preprocess.py"
# augment = "python src/augment.py"
# visualize = "python src/visualize.py"

[dependencies]

python = ">=3.9,<3.12"
pytorch = {version=">=2.4.1,<3", channel="pytorch"}
pytorch-cuda = "12.4"
numpy = "*"
scikit-learn = "*"
matplotlib = "*"
jupyter = "*"
tqdm = "*"
pillow = "*"

ipykernel = "*"
psutil = ">=5.9.8,<5.10.dev0"
pandas = ">=2.2.3,<3"

anndata = ">=0.11.4,<0.12"
seaborn = ">=0.13.2,<0.14"
umap-learn = ">=0.5.9.post2,<0.6"
torchinfo = ">=1.8.0,<2"

[target.linux-64.dependencies]
scikit-misc = ">=0.1.4,<0.2"  # Apparently not available on windows
