[workspace]
authors = ["copilot-swe-agent[bot] <198982749+Copilot@users.noreply.github.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "cropxr-example"
platforms = ["linux-64"]
version = "0.1.0"
description = "Data and DL model example for CropXR project"

[tasks]
train = "python src/train.py"
preprocess = "python src/preprocess.py"
augment = "python src/augment.py"
visualize = "python src/visualize.py"

[dependencies]
python = ">=3.9,<3.12"
pytorch = "*"
torchvision = "*"
torchaudio = "*"
numpy = "*"
pandas = "*"
scikit-learn = "*"
matplotlib = "*"
seaborn = "*"
jupyter = "*"
tqdm = "*"
pillow = "*"
opencv = "*"
tensorboard = "*"

# Optional CUDA dependencies - install if you have CUDA-compatible hardware
[feature.cuda.dependencies]
pytorch-cuda = "12.*"

# Optional development dependencies
[feature.dev.dependencies]
pytest = "*"
black = "*"
flake8 = "*"

[environments]
default = { solve-group = "default" }
cuda = { features = ["cuda"], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
cuda-dev = { features = ["cuda", "dev"], solve-group = "default" }
